// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function Systray() {
  return window['go']['main']['App']['Systray']();
}
