name: Build and Publish

on: [push, pull_request]

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: snapresolve, platform: linux/amd64, os: ubuntu-latest},
          {name: snapresolve, platform: windows/amd64, os: windows-latest},
          {name: snapresolve, platform: darwin/universal, os: macos-latest}
          {name: snapresolve, platform: darwin/universal, os: macos-15-large}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          go-version: "1.22"
          sign: true
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}